"""Ajout des tags

Revision ID: 455557a83789
Revises: 65b60695d1b0
Create Date: 2021-03-19 16:16:44.948673

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "455557a83789"
down_revision = "65b60695d1b0"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "amendement_tag",
        sa.Column("pk", sa.Integer(), nullable=False),
        sa.Column("label", sa.Text(), nullable=False),
        sa.Column("user_table_pk", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_table_pk"],
            ["user_tables.pk"],
            name=op.f("amendement_tag_user_table_pk_fkey"),
        ),
        sa.PrimaryKeyConstraint("pk"),
        sa.UniqueConstraint("user_table_pk", "label", name="_label_by_user_table_pk"),
    )
    op.create_table(
        "amendement_location2tag",
        sa.Column("tag_pk", sa.Integer(), nullable=False),
        sa.Column("amendement_location_pk", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["amendement_location_pk"],
            ["amendement_location.pk"],
            name=op.f("amendement_location2tag_amendement_location_pk_fkey"),
        ),
        sa.ForeignKeyConstraint(
            ["tag_pk"],
            ["amendement_tag.pk"],
            name=op.f("amendement_location2tag_tag_pk_fkey"),
        ),
        sa.PrimaryKeyConstraint("tag_pk", "amendement_location_pk"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("amendement_location2tag")
    op.drop_table("amendement_tag")
    # ### end Alembic commands ###
