"""Ajout table actualites

Revision ID: 9c1f8e962399
Revises: d34231284b19
Create Date: 2020-12-29 13:05:48.848541

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "9c1f8e962399"
down_revision = "d34231284b19"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "actualite",
        sa.Column("pk", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("file_name", sa.Text(), nullable=True),
        sa.Column("file_content_type", sa.Text(), nullable=True),
        sa.Column("file_data", sa.LargeBinary(), nullable=True),
        sa.Column("message", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("pk"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("actualite")
    # ### end Alembic commands ###
